# Generated by Django 3.1.6 on 2021-02-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meme_caption', models.CharField(max_length=200)),
                ('meme_url', models.URLField()),
            ],
        ),
    ]
